# Generated by Django 4.2.28 on 2026-02-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_notification_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('password_change', 'Password Change'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_deactivate', 'User Deactivated'), ('report_submit', 'Report Submitted'), ('report_review', 'Report Reviewed'), ('comment_add', 'Comment Added'), ('report_period_create', 'Reporting Period Created'), ('report_period_close', 'Reporting Period Closed'), ('report_period_reopen', 'Reporting Period Reopened'), ('report_revision_requested', 'Report Revision Requested')], max_length=30),
        ),
    ]
