# Generated by Django 4.2.28 on 2026-02-18 11:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='not_started', help_text='Current state in the report lifecycle', max_length=20)),
                ('accomplishments', models.TextField(blank=True, help_text='Accomplishments from the current week (required)', validators=[django.core.validators.MaxLengthValidator(3000)])),
                ('goals_next_week', models.TextField(blank=True, help_text='Goals for the upcoming week (required)', validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('blockers', models.TextField(blank=True, help_text='Blockers and challenges faced this week', validators=[django.core.validators.MaxLengthValidator(1500)])),
                ('support_needed', models.CharField(blank=True, help_text='Specific support needed from the supervisor', max_length=1000)),
                ('progress_rating', models.CharField(blank=True, choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('behind', 'Behind'), ('completed_early', 'Completed Early')], help_text='Overall progress rating for the week', max_length=20)),
                ('additional_notes', models.CharField(blank=True, help_text='Additional notes for the supervisor', max_length=1000)),
                ('is_late', models.BooleanField(default=False, help_text='Indicates if the report was submitted after the deadline')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp when the report was submitted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the report was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update to the report')),
                ('employee', models.ForeignKey(help_text='The employee who submitted this report', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(help_text='The reporting period this report belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.reportingperiod')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-period__start_date'],
                'indexes': [models.Index(fields=['employee', 'status'], name='reports_rep_employe_bebb20_idx'), models.Index(fields=['period', 'status'], name='reports_rep_period__fa6563_idx')],
                'unique_together': {('employee', 'period')},
            },
        ),
    ]
