# Generated by Django 4.2.28 on 2026-02-19 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', help_text='Current state in the report lifecycle', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 19, 23, 59, 59, tzinfo=datetime.timezone.utc), help_text='Submission deadline (Friday 11:59 PM)'),
        ),
    ]
