# Generated by Django 4.2.28 on 2026-02-20 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_status_alter_reportingperiod_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the report was marked as reviewed', null=True),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 20, 23, 59, 59, tzinfo=datetime.timezone.utc), help_text='Submission deadline (Friday 11:59 PM)'),
        ),
    ]
