# Generated by Django 4.2.28 on 2026-02-23 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_reviewed_at_alter_reportingperiod_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingperiod',
            name='closes_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled datetime to automatically close the period', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('draft', 'Draft'), ('revision_requested', 'Revision Requested'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', help_text='Current state in the report lifecycle', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 23, 23, 59, 59, tzinfo=datetime.timezone.utc), help_text='Submission deadline (Friday 11:59 PM)'),
        ),
    ]
