# Generated by Django 4.2.28 on 2026-02-26 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reportingperiod_closes_at_alter_report_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingperiod',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 26, 23, 59, 59, tzinfo=datetime.timezone.utc), help_text='Submission deadline (Friday 11:59 PM)'),
        ),
    ]
