# Generated by Django 4.2.28 on 2026-02-18 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0003_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('report_submitted', 'Report Submitted'), ('comment_added', 'Comment Added'), ('comment_reply', 'Comment Reply'), ('report_reviewed', 'Report Reviewed'), ('weekly_reminder', 'Weekly Reminder'), ('deadline_approaching', 'Deadline Approaching'), ('overdue_summary', 'Overdue Summary')], help_text='The type/category of notification', max_length=30)),
                ('message', models.CharField(help_text='Brief summary of the notification for display', max_length=255)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has viewed this notification')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the notification was created')),
                ('recipient', models.ForeignKey(help_text='The user who should receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_comment', models.ForeignKey(blank=True, help_text='Associated comment, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.comment')),
                ('related_report', models.ForeignKey(blank=True, help_text='Associated report, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.report')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
