# Generated by Django 4.2.28 on 2026-02-18 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('password_change', 'Password Change'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_deactivate', 'User Deactivated'), ('report_submit', 'Report Submitted'), ('report_review', 'Report Reviewed'), ('comment_add', 'Comment Added'), ('report_period_create', 'Reporting Period Created'), ('report_period_close', 'Reporting Period Closed')], max_length=30)),
                ('target_model', models.CharField(blank=True, max_length=50, null=True)),
                ('target_id', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action'], name='accounts_au_action_5ca9a9_idx'), models.Index(fields=['timestamp'], name='accounts_au_timesta_276167_idx')],
            },
        ),
    ]
