# Generated by Django 4.2.28 on 2026-02-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_required',
            field=models.BooleanField(default=True, help_text='Indicates if user needs to reset password on first login'),
        ),
    ]
