# Generated by Django 4.2.28 on 2026-02-18 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Monday of the reporting week')),
                ('end_date', models.DateField(help_text='Sunday of the reporting week')),
                ('deadline', models.DateTimeField(default=datetime.datetime(2026, 2, 18, 23, 59, 59, tzinfo=datetime.timezone.utc), help_text='Submission deadline (Friday 11:59 PM)')),
                ('is_closed', models.BooleanField(default=False, help_text='Indicates if the period is closed to new submissions')),
            ],
            options={
                'verbose_name': 'Reporting Period',
                'verbose_name_plural': 'Reporting Periods',
                'ordering': ['-start_date'],
                'unique_together': {('start_date', 'end_date')},
            },
        ),
    ]
