# Generated by Django 4.2.28 on 2026-02-18 13:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Comment content (plain text in v1)', validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the comment was created')),
                ('author', models.ForeignKey(help_text='The user who created this comment', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment for threading (one-level only in v1)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reports.comment')),
                ('report', models.ForeignKey(help_text='The report this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.report')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['report'], name='reports_com_report__84e28c_idx'), models.Index(fields=['author'], name='reports_com_author__5c0c81_idx')],
            },
        ),
    ]
